config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :introductions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/introduction.rb
class Introduction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController
  before_action :set_introduction, only: [:show, :edit, :update, :destroy]

  # GET /introductions
  # GET /introductions.json
  def index
    @introductions = Introduction.all
  end

  # GET /introductions/1
  # GET /introductions/1.json
  def show
  end

  # GET /introductions/new
  def new
    @introduction = Introduction.new
  end

  # GET /introductions/1/edit
  def edit
  end

  # POST /introductions
  # POST /introductions.json
  def create
    @introduction = Introduction.new(introduction_params)

    respond_to do |format|
      if @introduction.save
        format.html { redirect_to @introduction, notice: 'Introduction was successfully created.' }
        format.json { render :show, status: :created, location: @introduction }
      else
        format.html { render :new }
        format.json { render json: @introduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /introductions/1
  # PATCH/PUT /introductions/1.json
  def update
    respond_to do |format|
      if @introduction.update(introduction_params)
        format.html { redirect_to @introduction, notice: 'Introduction was successfully updated.' }
        format.json { render :show, status: :ok, location: @introduction }
      else
        format.html { render :edit }
        format.json { render json: @introduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /introductions/1
  # DELETE /introductions/1.json
  def destroy
    @introduction.destroy
    respond_to do |format|
      format.html { redirect_to introductions_url, notice: 'Introduction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_introduction
      @introduction = Introduction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def introduction_params
      params.require(:introduction).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/introductions_helper.rb
module IntroductionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/introductions/_form.html.erb
<%= form_for(introduction) do |f| %>
  <% if introduction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(introduction.errors.count, "error") %> prohibited this introduction from being saved:</h2>

      <ul>
      <% introduction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/introductions/edit.html.erb
<h1>Editing Introduction</h1>

<%= render 'form', introduction: @introduction %>

<%= link_to 'Show', @introduction %> |
<%= link_to 'Back', introductions_path %>

app/views/introductions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Introductions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @introductions.each do |introduction| %>
      <tr>
        <td><%= introduction.name %></td>
        <td><%= introduction.description %></td>
        <td><%= link_to 'Show', introduction %></td>
        <td><%= link_to 'Edit', edit_introduction_path(introduction) %></td>
        <td><%= link_to 'Destroy', introduction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Introduction', new_introduction_path %>

app/views/introductions/new.html.erb
<h1>New Introduction</h1>

<%= render 'form', introduction: @introduction %>

<%= link_to 'Back', introductions_path %>

app/views/introductions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @introduction.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @introduction.description %>
</p>

<%= link_to 'Edit', edit_introduction_path(@introduction) %> |
<%= link_to 'Back', introductions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BizHandson</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>